#!/bin/bash

########################################################################

usage() {
  this="$(basename "$0")"

  cat <<EOF

Load website logs into an SQLite virtual table where they
can be queried with SQL.

Currently only supports the Apache HTTPD access log file for
a website that follows EuPathDB's file naming and location
conventions.

Usage:
  $this <hostname>

Examples:
 $this dev.toxodb.org

This utility is experimental and unsupported.
EOF

  exit 1
}

########################################################################
# MAIN
########################################################################

test -z $1 && usage;

HOST=$1
ACCESS_LOG="/var/log/httpd/${HOST}/access_log"
ERROR_LOG="/var/log/httpd/${HOST}/error_log"

if [[ ! -e "$ACCESS_LOG" ]]; then
  echo "log not found: $ACCESS_LOG"
  exit 1
fi

if [[ ! -e "$ERROR_LOG" ]]; then
  echo "log not found: $ERROR_LOG"
  exit 1
fi

INIT="
.prompt 'cattoy> '
.load access_log.so
.load error_log.so
create virtual table access_log using access_log('$ACCESS_LOG');
create virtual table error_log using error_log('$ERROR_LOG');
"
echo "$INIT"

sqlite3 -init <(echo "$INIT")
